[[bin]]
name = "nvprime"
path = "src/bin/client.rs"

[[bin]]
name = "nvprime-sys"
path = "src/bin/daemon.rs"

[package]
name = "primers"
version = "0.1.0"
edition = "2024"
authors = ["The quick brown fox jumps over the lazy dog"]
description = "Minimalist NVIDIA PRIME render offload wrapper with config support"
license = "MIT"

[dependencies]
log = "0.4"
libc = "0.2"
chrono = "0.4"
env_logger = "0.11"

dirs = "5.0"
zbus = "5.0"
toml = "0.9"
anyhow = "1.0"
nvml-wrapper = "0.11"

nix = { version = "0.30", features = ["user", "resource"] }
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.48", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
