[package]
name = "prime-rs"
version = "0.1.0"
edition = "2024"
description = "Minimalist NVIDIA PRIME render offload wrapper with config support"
license = "MIT"

[dependencies]
dirs = "5.0"
toml = "0.9"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
