[workspace]
members = [
    "common",
    "client",
    "daemon",
]
resolver = "2"

[workspace.package]
name = "nvprime"
version = "0.1.0"
edition = "2024"
authors = ["The quick brown fox jumps over the lazy dog"]
description = "Minimalist NVIDIA PRIME render offload wrapper with config support"
license = "MIT"

[workspace.dependencies]
log = "0.4"
chrono = "0.4"
env_logger = "0.11"

zbus = "5.0"
dirs = "5.0"
anyhow = "1.0"

nix = { version = "0.30", features = ["user"] }
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.48", features = ["full"] }
